### ISSUE TITLE
Fix architecture

### ISSUE THREAD

**Issue by jcavat** [jcavat/LibellID#13]

**Comment by jcavat** [comment]
Don't put files into www folder. It's where ionic generate code. If we apply a ionic clean, this folder is removed. Look at this resources : [http://moduscreate.com/ionic-2-project-structure/](http://moduscreate.com/ionic-2-project-structure/) and [http://codingthesmartway.com/ionic-2-project-structure/](http://codingthesmartway.com/ionic-2-project-structure/).

Maybe you should put your files in an app folder. Put the resources inside app/assets. Change src to app and put all your component inside app.

**Comment by kodeiine** [comment]
Images and json have been moved in src/assets
