### ISSUE TITLE
Add an observation

### ISSUE THREAD

**Issue by kodeiine** [jcavat/LibellID#14]
https://wiki.biolovision.net/index.php/API/v1#Create_an_observation

Pending authorization

**Comment by VRosset** [comment]
![image](https://user-images.githubusercontent.com/32202706/31339299-b55a165a-ad02-11e7-8aa6-51239194bbb9.png)

**Comment by cicciu** [comment]
Duplicate of #31

**Comment by VRosset** [comment]
Pour le champ "Méthode", on l'oublie pour l'instant. Il n'est sûr qu'il soit dans l'API.

**Comment by VRosset** [comment]
Pour les champs dans l'APK du jour:
Remplacer "Nom de la lib.." par "Espèce observée"
Ajouter également un champ "Date"
Ajouter un champ " Email de l'utilisateur" avec un avertissement qu'il est nécessaire pour la vérification éventuelle des données, mais ne sera pas utilisé à d'autres fins.
Afficher la photo plus petite et afficher plutôt un picto d'un appareil photo tant que l'utilisateur n'a rien uploadé.
Les champs "Espèce", "Date", "Lieu" doivent se pré-remplir avec les données du téléphone et de l'application (pour espèce: si l'utilisateur clique sur transmettre une observation quand il arrive sur une fiche espèce depuis l'outil d'identification)
Ajouter un champ masqué "Label": toujours rempli par Libellulid qui est envoyé en même temps que les champs visibles vers ornitho.ch

**Comment by VRosset** [comment]
J’ai créé un compte sur ornitho.ch avec le mail de l’application: libellulid@hesge.ch.
Le mot de passe sur ornitho.ch est : [REMOVED]

**Comment by VRosset** [comment]
les clefs d’accès :

consumer_key : [REMOVED]
consumer_secret : [REMOVED]

Le endpoint c’est https://www.ornitho.ch (il faut bien utiliser le https. Pour le moment, cela marche sans le s mais probablement plus l’avenir).

L’API doit être liée au compte libellulid@hesge.ch, il faut donc utiliser cet email et le mot de passe associé pour y accéder.

La doc est ici : https://wiki.biolovision.net/index.php/API/v1

**Comment by VRosset** [comment]
Est-ce possible de regrouper Nom et Prénom avec l'email?
Pour l'email, écrire seulement "Email" sans "de l'utilisateur"

Est-ce possible également d'avoir la case à cocher pour inconnu juste à côté de "Nombre d'individus" sur la même ligne et de la nommer uniquement "Inconnu"?

Il faudrait ajouter un "s" à inconnu dans la catégorie "Nb individus"

**Comment by VRosset** [comment]
Il faudrait que l'utilisateur puisse charger une photo depuis sa galerie plutôt que de faire une photo en direct.

**Comment by VRosset** [comment]
Le Label "Libellul'ID" ne doit pas être visible de l'utilisateur.
Très bonne idée le classement en 2 catégories: Peux-tu changer "Données de l'espèce" par "Information sur l'espèce" et "Données utilisateur" par "Informations sur l'utilisateur"?
Est-il possible de faire en sorte que le nb d'individus par défaut soit 1 au lieu de 0?
Il ne faut pas de s à Inconnu (je me suis trompée dans mon commentaire précédent, désolée)
Est-ce que le texte en rouge peut être en gris pour faire moins agressif?
La ligne verte sous nb individus est perturbante. Peu-ton avoir un trait gris clair comme pour les autres lignes? [OK]
