### ISSUE TITLE
Add "about" page

### ISSUE THREAD

**Issue by kodeiine** [jcavat/LibellID#15]

**Comment by VRosset** [comment]
Les différentes images à insérer: 
![cycle de vie odonate](https://user-images.githubusercontent.com/32202706/36435375-c856291a-1661-11e8-8967-95f57bad55ff.png)
![copue_photocarre](https://user-images.githubusercontent.com/32202706/36435381-cfb1a66c-1661-11e8-9271-056a05adcd1b.png)
![libellule-taches-menu](https://user-images.githubusercontent.com/32202706/36435682-9f318f2e-1662-11e8-8a78-f2e0fbba4df2.jpg)

**Comment by VRosset** [comment]
Le contenu du menu à propos est ci-joint:
[3 Contenu menu à propos V2.docx](https://github.com/jcavat/LibellID/files/1740927/3.Contenu.menu.a.propos.V2.docx)
Les logos sont dans la Dropbox.

**Comment by VRosset** [comment]
Il reste quelques petits changements à faire dans l'A propos:
- Rajouter un enter supplémentaire avant chaque titre en police standard souligné (pex cycle de vie d'une libellule)
- Rajouter un enter supplémentaire avant chaque logo.
- Pour les pictos que tu as pris pour les accès, modifier le titre: "Crédits pour les icônes décrivant les modalités d'accessibilité des itinéraires"
