### ISSUE TITLE
Add data for all dragonflies (autres/fiches infos)

### ISSUE THREAD

**Issue by kodeiine** [jcavat/LibellID#16]

**Comment by VRosset** [comment]
En cours aujourd'hui et demain. Je travaille sur une copie du .json.
Véronique

**Comment by VRosset** [comment]
Il faudrait modifier (parties en gras) dans le code le texte de l'onglet Infos et du chapitre "Pour en savoir plus", je n'y ai pas accès:
Un site web présente toutes les libellules de Suisse : www.libellen**schutz**.ch
Une application smartphone avec un outil d’identification des libellules de Suisse plus précis mais plus complexe **a été développée** par le Centre Suisse de Cartographie de la Faune CSCF.
[OK]

**Comment by VRosset** [comment]
Les fiches des "femelles et immatures jaunes" et des "Libellules supplémentaires" ne fonctionnent pas. Il faut filtrer les informations affichées pour ces 2 groupes en fonction de "info_level" dans le JSON. [OK]

**Comment by VRosset** [comment]
Il manque également encore le tableau des périodes de vol (dégradés de vert) qui doit se remplir en fonction des infos dans le JSON. [OK]

**Comment by VRosset** [comment]
Quand on clique sur le lien libellenschutz.ch, cela bug. [OK]
