### ISSUE TITLE
Geolocation filter

### ISSUE THREAD

**Issue by jcavat** [jcavat/LibellID#23]

**Comment by VRosset** [comment]
En plus du filtre selon les périodes de vol, il faut que si l'utilisateur est dans le canton de Genève, les espèces: Cordulia aenea, Cordulegaster boltonii et Erythromma viridulum s'affichent et non le groupe des Cordulies, le groupe des naïades et le groupe des Cordulégastres (et vice-versa s'il est ailleurs).

**Comment by cicciu** [comment]
Que se passe-t-il si on se trouve proche d'une frontière ou dans une enclave ?

**Comment by VRosset** [comment]
Je peux vous donner des infos plus précises pour pouvoir coder cette partie demain. J’ai presque fini.
Véronique

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : lundi 9 octobre 2017 17:20
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; State change <state_change@noreply.github.com>
Objet : Re: [jcavat/LibellID] Geolocation filter (#23)


Que se passe-t-il si on se trouve proche d'une frontière ou dans une enclave ?

**Comment by VRosset** [comment]
![image](https://user-images.githubusercontent.com/32202706/31370963-bbe09bca-ad8e-11e7-9a67-eeb86acaa4c3.png)

**Comment by VRosset** [comment]
Pour répondre à la question d'hier, si on est hors du canton de Genève, on garde les 3 groupes de droite (Cordulies de plaine, Cordulégastres, Naïades) qu'on soit ailleurs en Suisse, en France ou n'importe où ailleurs dans le monde.
On peut imaginer garder une zone tampon de 500m avant de basculer, mais il faudrait voir ce qui est fait usuellement.
L'enclave de Céligny compte comme Suisse romande.

**Comment by VRosset** [comment]
L'application ne semble pas faire de demande de localisation au GPS, ni pour les filtres par position, ni pour insérer la position dans le module de saisie des informations.
