### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by jcavat** [jcavat/LibellID#24]

**Comment by VRosset** [comment]
![image](https://user-images.githubusercontent.com/32202706/31370949-a9ea99de-ad8e-11e7-9bcc-6a7b3723a3e6.png)

**Comment by VRosset** [comment]
Je suis en train de préparer la table périodes de vol pour toutes les espèces.
Je vais insérer ces données ensuite de le .json 
Ce sont les mêmes données de périodes de vol qui sont utilisées pour les fiches infos et pour ce filtre.
Pour les fiches infos, nuances de vert en fonction des chiffres (1,2,3). Pour le filtre de date, se baser uniquement sur la présence-absence.

**Comment by VRosset** [comment]
[matrice_periodes_vol_par_semaines.xlsx](https://github.com/jcavat/LibellID/files/1371381/matrice_periodes_vol_par_semaines.xlsx)
