### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by jcavat** [jcavat/LibellID#25]

**Comment by cicciu** [comment]
Je vais m'occuper de créer la page. Pouvez-vous me transmettre le texte/images/ressources à mettre dessus ?

**Comment by VRosset** [comment]
Bonjour,
Les ressources à mettre sont en cours de conception.
Je vous les fais parvenir dès qu’elles sont prêtes. Probablement encore 1 mois.

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : lundi 9 octobre 2017 17:18
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; Assign <assign@noreply.github.com>
Objet : Re: [jcavat/LibellID] Help page (#25)


Je vais m'occuper de créer la page. Pouvez-vous me transmettre le texte/images/ressources à mettre dessus ?

**Comment by VRosset** [comment]
Bonjour,
Les éléments pour l'aide (? en haut à droite du menu quand on est dans la partie "Identifier" sont prêts.
Il s'agit du texte ci-joint.
[2 Contenu aide identification.docx](https://github.com/jcavat/LibellID/files/1446022/2.Contenu.aide.identification.docx)

**Comment by VRosset** [comment]
Voici le texte pour la deuxième aide (? à ajouter en haut à droite du menu quand on est dans les résultats d'une identification).
[3 Contenu aide identification resultats.docx](https://github.com/jcavat/LibellID/files/1706984/3.Contenu.aide.identification.resultats.docx)

**Comment by VRosset** [comment]
Il faudrait ajouter un paragraphe dans l'aide sur la page des résultats de l'identification (espèces classées par probabilité):
**Si aucune libellule ne s'affiche**, c'est qu'elles ne volent pas à cette saison. Vous pouvez dé-sélectionner le filtre par date en haut à droite de l'écran précédant.

Je te remercie d'avance.
