### ISSUE TITLE
Colours 

### ISSUE THREAD

**Issue by VRosset** [jcavat/LibellID#38]
Dans le menu Identifier:
- Reduce the size of the colours (si possible 4 lignes de 4 couleurs,cf tableau ci-dessous) dans la largeur de l'écran (sans défilement) et sur la même hauteur environ qu'actuellement

- Change the colours:
La nouvelle liste de couleur est:

![image](https://user-images.githubusercontent.com/32202706/31615476-f9d52f7c-b289-11e7-806b-f2790be63553.png)

L'ordre dans le .json est dans le sens de lecture de haut en bas et de gauche à droite.

Les éléments en rouge sont nouveaux ou différents et donc à modifier dans l'application.

**Comment by cicciu** [comment]
Pour les nouvelles images de couleurs, on se fait un Dropbox partager?

**Comment by VRosset** [comment]
Le plus simple serait de les mettre sur le serveur P.
Y avez-vous accès ?
Sinon, une Dropbox ok.

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : lundi 6 novembre 2017 11:56
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; Author <author@noreply.github.com>
Objet : Re: [jcavat/LibellID] Colours (#38)


Pour les nouvelles images de couleurs, on se fait un Dropbox partager?

**Comment by cicciu** [comment]
On a pas accès au serveur, mais ok pour Dropbox.

*__*  *Salvatore Cicciù*
            Étudiant Master - HES-SO
            Technologies de l'Information et de la Communication (TIC)
            Ingénierie logicielle

            Tel +41 79 728 80 57

**Comment by VRosset** [comment]
Par contre, la peinture n’est pas encore sèche.
Je vous ferai parvenir les photos d’ici 2 semaines environ.
Véronique

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : lundi 6 novembre 2017 12:01
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; Author <author@noreply.github.com>
Objet : Re: [jcavat/LibellID] Colours (#38)

On a pas accès au serveur, mais ok pour Dropbox.

*__* *Salvatore Cicciù*
Étudiant Master - HES-SO
Technologies de l'Information et de la Communication (TIC)
Ingénierie logicielle

Tel +41 79 728 80 57

Le 6 novembre 2017 à 11:57, VRosset <notifications@github.com<mailto:notifications@github.com>> a écrit :

> Le plus simple serait de les mettre sur le serveur P.
> Y avez-vous accès ?
> Sinon, une Dropbox ok.
>
> De : Salvatore Cicciu [mailto:notifications@github.com]
> Envoyé : lundi 6 novembre 2017 11:56
> À : jcavat/LibellID <LibellID@noreply.github.com<mailto:LibellID@noreply.github.com>>
> Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch<mailto:Veronique.Rosset@hesge.ch>>; Author <
> author@noreply.github.com<mailto:author@noreply.github.com>>
> Objet : Re: [jcavat/LibellID] Colours (#38)
>
>
> Pour les nouvelles images de couleurs, on se fait un Dropbox partager?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<https://github.com/
<https://github.com/%0b>> jcavat/LibellID/issues/38#issuecomment-342114535>, or mute the thread<

**Comment by cicciu** [comment]
D'accord ça joue.
Si jamais au moment où il faudra me partager le dossier Dropbox, l'adresse
mail est la même que celle-ci <salvatore.cicciu@gmail.com>

*__*  *Salvatore Cicciù*
            Étudiant Master - HES-SO
            Technologies de l'Information et de la Communication (TIC)
            Ingénierie logicielle

            Tel +41 79 728 80 57

**Comment by VRosset** [comment]
J'ai mis les 3 photos de couleur manquantes dans la Dropbox, elles sont numérotées dans l'ordre de la première ligne du tableau ci-dessus (1er commentaire).
Véronique

**Comment by VRosset** [comment]
@cicciu : Tu m'as dit que le rouge écarlate est en position 8 pour toi, mais selon le tableau ci-dessus du 16 octobre, il n'existe plus et c'est le jaune qui est en position 8. Je pense que tu n'as appliqué les modifications de ce tableau. 
Peux-tu essayer?

**Comment by VRosset** [comment]
J'ai vérifié les couleurs dans le menu Identifier.
Il reste un seul bug. 
L'Aeschne bleue (la première libellule dans le json) apparaît quand on sélectionne les couleurs brun-orangé et rouge (13e et 14e positions) alors qu'elle ne devrait pas et que le json est ok (je viens de vérifier).
Véronique

**Comment by cicciu** [comment]
Bonjour Véronique,

Lorsque je selectionne les couleurs brun-orangé et rouge, j'obtiens la
liste suivante:



AeSne isocèle 1/1
Libellule à quatre taches 1/1
Libellule écarlate 1/1
Petite nymphe au corps de feu 1/1
Sympértums rouges 1/1

Et ensuite..

Aeschne bleue 0/0
Aes....



Cela m'a l'air correcte non? Si tu ressaye tu n'as pas la même chose sur
ton téléphone?




*__*  *Salvatore Cicciù*
            Étudiant Master - HES-SO
            Technologies de l'Information et de la Communication (TIC)
            Ingénierie logicielle

            Tel +41 79 728 80 57
