### ISSUE TITLE
Map does not work anymore

### ISSUE THREAD

**Issue by VRosset** [jcavat/LibellID#41]
Depuis le nouvel APK (16.10.2017), les fonds de carte ne s'affichent pas, ni dans la vue d'ensemble des itinéraires, ni derrière l'itinéraire lui-même.

**Comment by cicciu** [comment]
Les maps de la vue Promenades?

**Comment by VRosset** [comment]
Oui, dans la liste des promenades et quand on fait une promenade.

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : jeudi 19 octobre 2017 10:13
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; Author <author@noreply.github.com>
Objet : Re: [jcavat/LibellID] Map does not work anymore (#41)


Les maps de la vue Promenades?

**Comment by cicciu** [comment]
the problem was that the following plugin was not installed or not save.

`cordova plugin add cordova-plugin-whitelist --save`
