### ISSUE TITLE
Change the screens describing the walks

### ISSUE THREAD

**Issue by VRosset** [jcavat/LibellID#43]
Il faudrait modifier la structure de la page d'accueil avec la liste des itinéraires ainsi que la page décrivant chaque itinéraire en détail en fonction de la première page du compte-rendu ci-joint.
[Compte rendu reunion LibellID 19oct17.docx](https://github.com/jcavat/LibellID/files/1446525/Compte.rendu.reunion.LibellID.19oct17.docx)

Le picto de libellule à utiliser est celui-ci:
![couleur01-01](https://user-images.githubusercontent.com/32202706/32446038-eededbf2-c307-11e7-8624-ba975065c331.png)

**Comment by cicciu** [comment]
"walks": [
    {
      "id": 1,
      "name": "Jardin botanique",
      "preview": "walk1-preview1.png",
      "duration": "1h15",
      "diversity": 2,
      "period":"Avril à octobre",
      "difficulty": 1,
      "length": 3.1,
      "description": "",
      "Accessibility":[0,1,4],
      "Infrastructure":"bélal fdkdk",
      "Info":"ckjf ojfo kj",
      "Access":"kjdojdo  dokjodjd d i"
    },

**Comment by VRosset** [comment]
L'ordre des pictos "Access" (handicapés, pousettes,...) est bien identique dans le JSON et dans le document Word posté le 6 Novembre.
Véronique

**Comment by VRosset** [comment]
Quelques petites modifications encore à faire:
- Certains textes sont devenus trop petits, illisibles déjà sur un Samsung S4. Par exemple, tableau des critères sur la 1e page des fiches infos, écran décrivant les itinéraires.
- Le logo de libellule que j'ai fourni ne fonctionne pas (il est trop fin). Il faudrait épaissir les traits et augmenter la taille des libellules (dans la liste des itinéraires, elles peuvent prendre deux lignes dans le tableau par exemple)
- Pour les rubriques access, infrastructure et divers, il faut le texte soit aligné (voir par exemple itinéraire les étangs de Bonfol pour divers.
- Il faudrait uniquement 3 barres pour la variété de libellules au lieu de 4 actuellement (car il n'y a que 3 catégories).
- Il faudrait que les liens Internet soient cliquables (par exemple Maison de la Rivière).
