### ISSUE TITLE
Bug maps in the walks

### ISSUE THREAD

**Issue by VRosset** [jcavat/LibellID#47]
Bonjour Salvatore,
La carte ne s'affiche de nouveau pas quand on est dans les itinéraires (il y a peut-etre à nouveau eu une mise à jour).
Je dois faire une démo à un partenaire financier mardi prochain le 5 décembre. Il faudrait que cela soit résolu d'ici là. 
Merci d'avance!
Véronique

**Comment by cicciu** [comment]
Bonsoir Véronique,

Est ce que tu as téléchargé la dernière version de l'application, si c'est
pas le cas il faut la télécharger sur le lien suivant:

https://github.com/jcavat/LibellID/raw/master/apk/android-debug.apk

Si s'était déjà le cas, est ce que les données mobiles sont activées, pour
que la map puisse être charger une fois?

*__*  *Salvatore Cicciù*
            Étudiant Master - HES-SO
            Technologies de l'Information et de la Communication (TIC)
            Ingénierie logicielle

            Tel +41 79 728 80 57

**Comment by VRosset** [comment]
Bonjour Salvatore,
Cela fonctionne avec la nouvelle APK. Désolée pour le dérangement.
Je vais fermer l’issue.
Véronique

De : Salvatore Cicciu [mailto:notifications@github.com]
Envoyé : mardi 28 novembre 2017 20:16
À : jcavat/LibellID <LibellID@noreply.github.com>
Cc : Rosset Véronique (HES) <Veronique.Rosset@hesge.ch>; Author <author@noreply.github.com>
Objet : Re: [jcavat/LibellID] Bug maps in the walks (#47)

Bonsoir Véronique,

Est ce que tu as téléchargé la dernière version de l'application, si c'est
pas le cas il faut la télécharger sur le lien suivant:

https://github.com/jcavat/LibellID/raw/master/apk/android-debug.apk

Si s'était déjà le cas, est ce que les données mobiles sont activées, pour
que la map puisse être charger une fois?

*__* *Salvatore Cicciù*
Étudiant Master - HES-SO
Technologies de l'Information et de la Communication (TIC)
Ingénierie logicielle

Tel +41 79 728 80 57
