### ISSUE TITLE
bug avec bandeau identifier/voir

### ISSUE THREAD

**Issue by demierree** [jcavat/LibellID#60]
On m'a signalé un bug avec la version du 27 août 2018 installée sur un Samsung edge 7, le bandeau du  menu voir / recommencer dans la partie identification ne reste plus en bas il remonte avec les image quand on scroll vers le bas (voir image). J'ai essayé en installant la dernière version sur un s6 edge, je n'ai pas constaté le problème.
![screenshot_20190123-205601_libellul id](https://user-images.githubusercontent.com/40020704/51662592-9bcd2d00-1fb4-11e9-91a9-9fbdd796cca5.jpg)

**Comment by briannydegger** [comment]
Impossible de reproduire le problème
